name: Build and release firmware (develop)
on:
  push:
    branches:
      - develop
      - feature-14-new-distribution-system
jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""

      - name: Update version to platformio.ini
        run: |
          echo "Updating version to ${{ steps.tag_version.outputs.new_tag }}"
          
          sed -i 's/release_version =.*/release_version = ${{ steps.tag_version.outputs.new_tag }}/g' platformio.ini
          
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add platformio.ini
          git commit -m "Updated version"

      - name: Push version changes to develop
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -e release

      - name: Create version.txt
        run: |
          echo ${{ steps.tag_version.outputs.new_tag }} > version.txt

      - name: Upload firmware.bin
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.UPDATES_BUCKET }}
          source_dir: .pio/build/release/firmware.bin
          destination_dir: ${{ secrets.UPDATES_BUCKET_PATH }}

      - name: Upload version.txt
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.UPDATES_BUCKET }}
          source_dir: version.txt
          destination_dir: ${{ secrets.UPDATES_BUCKET_PATH }}